/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import itson.ticketwizard.control.ControlBoletos;
import itson.ticketwizard.control.ControlMovimientos;
import itson.ticketwizard.entidades.Boleto;
import itson.ticketwizard.entidades.Seguridad;
import itson.ticketwizard.excepciones.TransaccionException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Peter
 */
public class PnlConfirmarCompra extends javax.swing.JPanel {

    private ControlBoletos control;
    private List<Boleto> boletos;
    private FrmPrincipal parent;
    private ControlMovimientos controlMovimientos;
    private double monto;
    
    /**
     * Creates new form NewJPanel
     */
    public PnlConfirmarCompra(ControlBoletos control, List<Boleto> boletos, FrmPrincipal parent, ControlMovimientos controlMovimientos ) {
        this.control = control;
        this.boletos = boletos;
        this.parent = parent;
        this.controlMovimientos = controlMovimientos;
        initComponents();
        cargarPanel();
    }
    
    /**
     * Metodo para cargar la información de la compra
     */
    private void cargarPanel(){
        String asientos = "";
        double monto = 0;
        for(Boleto boleto : boletos){
            asientos+= boleto.getFila()+String.valueOf(boleto.getAsiento());
            monto += boleto.getPrecio();
            if(!boletos.getLast().equals(boleto)){
                asientos+= ", ";
                
            }
        }
        lblNumBoletos.setText(boletos.size()+ " Boletos");
        Boleto boleto = boletos.getFirst();
        this.monto = monto;
        lblMonto.setText("Monto: $"+String.valueOf(monto)+"MXN");
        lblNombre.setText("* Evento: "+ control.consultaEvento(boleto));
        lblSaldo.setText("Saldo actual: "+String.valueOf(parent.getUsuario().getSaldo()));
        lblAsientos.setText("Asientos: "+asientos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblNumBoletos = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        lblAsientos = new javax.swing.JLabel();
        btnConfirmarCompra = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(233, 233, 233));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Confirmar Compra");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lblNumBoletos.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblNumBoletos.setForeground(new java.awt.Color(30, 30, 30));
        lblNumBoletos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumBoletos.setText("n Boletos");

        lblMonto.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        lblMonto.setForeground(new java.awt.Color(30, 30, 30));
        lblMonto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMonto.setText("$0000 MXN");

        lblNombre.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(130, 130, 130));
        lblNombre.setText("* <Nombre Evento>");

        lblSaldo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblSaldo.setForeground(new java.awt.Color(130, 130, 130));
        lblSaldo.setText("* Saldo actual: <Saldo>");

        lblAsientos.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblAsientos.setForeground(new java.awt.Color(130, 130, 130));
        lblAsientos.setText("* Asientos: <Fila Asiento>");

        btnConfirmarCompra.setBackground(new java.awt.Color(0, 0, 0));
        btnConfirmarCompra.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnConfirmarCompra.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmarCompra.setText("Completar Compra");
        btnConfirmarCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarCompraActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(180, 0, 0));
        btnCancelar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar Compra");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumBoletos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMonto, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAsientos)
                    .addComponent(lblSaldo)
                    .addComponent(lblNombre))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNumBoletos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMonto)
                .addGap(18, 18, 18)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAsientos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConfirmarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
                parent, 
                "¿Seguro que desea cancelar la compra?", 
                "Confirmar Cancelar", 
                JOptionPane.ERROR_MESSAGE);
        if(opcion == JOptionPane.OK_OPTION){
            parent.mostrarEventos();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConfirmarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarCompraActionPerformed
        try{
            
            int opcion = JOptionPane.showConfirmDialog(
                    parent, 
                    "¿Seguro que desea confirmar la compra?", 
                    "Confirmar Compra", 
                    JOptionPane.YES_NO_OPTION);
            if(opcion == JOptionPane.YES_OPTION){
                for (Boleto boleto : boletos) {
                    if(boleto.getIdUsuario() != null){
                        controlMovimientos.comprarReventa(parent.getUsuario(), boleto.getIdBoleto(), boleto.getPrecio(), Seguridad.generarCodigoAlfanumerico(), boleto.getIdUsuario());
                    } else {
                        controlMovimientos.comprarBoletera(parent.getUsuario(), boleto.getIdBoleto(), boleto.getPrecio(), Seguridad.generarCodigoAlfanumerico());
                    }
                }
                JOptionPane.showMessageDialog(
                    parent, 
                    "Se ha realizado la compra", 
                    "Información", 
                    JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (TransaccionException exx){
            JOptionPane.showMessageDialog(
                    parent, 
                    "Hubo un error al hacer la transaccion: "+exx.getMessage(), 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConfirmarCompraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmarCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAsientos;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumBoletos;
    private javax.swing.JLabel lblSaldo;
    // End of variables declaration//GEN-END:variables
}