/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import itson.ticketwizard.control.ControlCompraBoletos;
import itson.ticketwizard.entidades.Boleto;
import java.util.LinkedList;
import java.util.List;
import javax.swing.Box;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class PnlComprarBoletos extends javax.swing.JPanel {

    private ControlCompraBoletos control;
    private FrmPrincipal parent;
    private Integer idEvento;
    private List<PnlBoletoComprar> listaPanelesBoletos;
    /**
     * Creates new form pnlComprarBoletos
     */
    public PnlComprarBoletos(ControlCompraBoletos control, FrmPrincipal parent, Integer idEvento) {
        this.control = control;
        this.parent = parent;
        this.idEvento = idEvento;
        this.listaPanelesBoletos = new LinkedList<>();
        initComponents();
        cargarBoletos();
    }

    private void cargarBoletos(){
        List<Boleto> boletos = control.consultarBoletosEvento(idEvento);
        for(Boleto boleto: boletos){
            PnlBoletoComprar panel = new PnlBoletoComprar(boleto, this);
            boxPnlBoletos.add(panel);
            boxPnlBoletos.add(Box.createVerticalStrut(30));
            listaPanelesBoletos.add(panel);
        }
    }

    public ControlCompraBoletos getControl() {
        return control;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        btnComprar = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        boxPnlBoletos = new javax.swing.JPanel();

        setBackground(new java.awt.Color(233, 233, 233));
        setForeground(new java.awt.Color(233, 233, 233));

        btnVolver.setBackground(new java.awt.Color(0, 0, 0));
        btnVolver.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnComprar.setBackground(new java.awt.Color(0, 0, 0));
        btnComprar.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        btnComprar.setForeground(new java.awt.Color(255, 255, 255));
        btnComprar.setText("Comprar Boletos");
        btnComprar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        scrollPane.setBackground(new java.awt.Color(233, 233, 233));
        scrollPane.setBorder(null);

        boxPnlBoletos.setBackground(new java.awt.Color(233, 233, 233));
        boxPnlBoletos.setLayout(new javax.swing.BoxLayout(boxPnlBoletos, javax.swing.BoxLayout.Y_AXIS));
        scrollPane.setViewportView(boxPnlBoletos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        parent.mostrarEventos();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        List<Boleto> boletos = new LinkedList<>();
        for (PnlBoletoComprar pnlBoleto : listaPanelesBoletos) {
            if(pnlBoleto.getCheckBox().isSelected()){
                boletos.add(pnlBoleto.getBoleto());
            }
        }
        if(boletos.isEmpty()){
            JOptionPane.showMessageDialog(
                    parent,
                    "No ha seleccionado ningún boleto",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        } else {
            parent.mostrarConfirmarCompra(boletos);
        }
    }//GEN-LAST:event_btnComprarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boxPnlBoletos;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
