/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import itson.ticketwizard.control.ControlMostrarEventos;
import itson.ticketwizard.dto.MostrarEventoDTO;
import java.util.LinkedList;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;

/**
 *
 * @author pc
 */
public class PnlEventos extends javax.swing.JPanel {

    private List<PnlEvento> listaEventos = new LinkedList<>();
    private ControlMostrarEventos control;
    private FrmPrincipal parent;
    /**
     * Creates new form pnlEventos
     */
    public PnlEventos(ControlMostrarEventos control, FrmPrincipal parent) {
        this.control = control;
        this.parent = parent;
        initComponents();
        this.cargarEventos();
    }
    
    private void cargarEventos(){
        List<MostrarEventoDTO> eventos = control.consultarEventos();
        for (MostrarEventoDTO evento : eventos) {
            PnlEvento pnlEvento = new PnlEvento(evento, this);
            boxPanelEventos.add(pnlEvento);
            boxPanelEventos.add(Box.createVerticalStrut(30));
            listaEventos.add(pnlEvento);
        }
        
    }
    
    public void mostrarBoletos(Integer idEvento){
        parent.mostrarBoletosEvento(idEvento);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEventos = new javax.swing.JPanel();
        panelEventos = new javax.swing.JScrollPane();
        boxPanelEventos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        pnlEventos.setBackground(new java.awt.Color(233, 233, 233));
        pnlEventos.setForeground(new java.awt.Color(30, 30, 30));

        panelEventos.setBackground(new java.awt.Color(233, 233, 233));

        boxPanelEventos.setLayout(new javax.swing.BoxLayout(boxPanelEventos, javax.swing.BoxLayout.Y_AXIS));
        panelEventos.setViewportView(boxPanelEventos);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Eventos Disponibles");

        javax.swing.GroupLayout pnlEventosLayout = new javax.swing.GroupLayout(pnlEventos);
        pnlEventos.setLayout(pnlEventosLayout);
        pnlEventosLayout.setHorizontalGroup(
            pnlEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEventosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelEventos, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEventosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(200, 200, 200))
        );
        pnlEventosLayout.setVerticalGroup(
            pnlEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEventosLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEventos, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 886, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlEventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlEventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boxPanelEventos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane panelEventos;
    private javax.swing.JPanel pnlEventos;
    // End of variables declaration//GEN-END:variables
}
