/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import itson.ticketwizard.dto.MostrarTransaccionDTO;
import java.util.List;

/**
 *
 * @author Peter
 */
public class PnlMovimiento extends javax.swing.JPanel {

    private List<MostrarTransaccionDTO> movimiento;
    private PnlMovimientos parent;
    
    /**
     * Creates new form PnlMovimiento
     */
    public PnlMovimiento(List<MostrarTransaccionDTO> movimiento, PnlMovimientos parent) {
        this.movimiento = movimiento;
        this.parent = parent;
        initComponents();
        cargarMovimiento();
    }

    private void cargarMovimiento(){
        String asientos = "";
        String compradoDe = "";
        for(MostrarTransaccionDTO parteMovimiento : movimiento){
            asientos+= parteMovimiento.getFila()+String.valueOf(parteMovimiento.getAsiento());
            compradoDe+= parteMovimiento.getTipoCompra();
            if(!movimiento.getLast().equals(parteMovimiento)){
                asientos+= ", ";
                compradoDe+=", ";
            }
        }
        MostrarTransaccionDTO nMovimiento = movimiento.getFirst();
        lblMonto.setText("Monto: $"+String.valueOf(nMovimiento.getMonto())+"MXN");
        lblFechaHora.setText("Fecha y Hora: "+nMovimiento.getFechaHora().toString());
        lblTipoCompra.setText("Comprado de: "+compradoDe);
        lblNombreEvento.setText("Evento: "+nMovimiento.getEvento());
        lblAsientos.setText("Asientos: "+asientos);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 32767));
        lblMonto = new javax.swing.JLabel();
        lblFechaHora = new javax.swing.JLabel();
        lblTipoCompra = new javax.swing.JLabel();
        lblNombreEvento = new javax.swing.JLabel();
        lblAsientos = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        filler1.setBackground(new java.awt.Color(0, 0, 0));

        lblMonto.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblMonto.setForeground(new java.awt.Color(30, 30, 30));
        lblMonto.setText("Monto: ");

        lblFechaHora.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblFechaHora.setForeground(new java.awt.Color(30, 30, 30));
        lblFechaHora.setText("Fecha y hora:");

        lblTipoCompra.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblTipoCompra.setForeground(new java.awt.Color(30, 30, 30));
        lblTipoCompra.setText("Comprado de: ");

        lblNombreEvento.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblNombreEvento.setForeground(new java.awt.Color(30, 30, 30));
        lblNombreEvento.setText("Nombre del Evento: ");

        lblAsientos.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblAsientos.setForeground(new java.awt.Color(30, 30, 30));
        lblAsientos.setText("Asientos: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAsientos)
                    .addComponent(lblTipoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblMonto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFechaHora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTipoCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombreEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAsientos)
                .addGap(83, 83, 83)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAsientos;
    private javax.swing.JLabel lblFechaHora;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblNombreEvento;
    private javax.swing.JLabel lblTipoCompra;
    // End of variables declaration//GEN-END:variables
}
