/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import itson.ticketwizard.control.ControlBoletos;
import itson.ticketwizard.entidades.Boleto;
import itson.ticketwizard.entidades.Seguridad;
import java.util.LinkedList;
import java.util.List;
import javax.swing.Box;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class PnlReventaBoletos extends javax.swing.JPanel {

    private List<Boleto> boletos;
    private List<PnlBoletoReventa> listaPaneles;
    private ControlBoletos control;
    private FrmPrincipal parent;

    /**
     * Creates new form PnlReventaBoletos
     */
    public PnlReventaBoletos(List<Boleto> boletos, ControlBoletos control, FrmPrincipal parent) {
        this.boletos = boletos;
        this.control = control;
        this.parent = parent;
        initComponents();
        cargarBoletos();
    }

    private void cargarBoletos() {
        listaPaneles = new LinkedList<>();
        for (Boleto boleto : boletos) {
            PnlBoletoReventa panel = new PnlBoletoReventa(boleto, parent);
            boxPanelBoletos.add(panel);
            boxPanelBoletos.add(Box.createVerticalStrut(30));
            listaPaneles.add(panel);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnlEventos = new javax.swing.JPanel();
        scrollPanelEventos = new javax.swing.JScrollPane();
        boxPanelBoletos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnRevender = new javax.swing.JButton();

        pnlEventos.setBackground(new java.awt.Color(233, 233, 233));
        pnlEventos.setForeground(new java.awt.Color(30, 30, 30));

        scrollPanelEventos.setBackground(new java.awt.Color(233, 233, 233));
        scrollPanelEventos.setBorder(null);

        boxPanelBoletos.setBackground(new java.awt.Color(233, 233, 233));
        boxPanelBoletos.setLayout(new javax.swing.BoxLayout(boxPanelBoletos, javax.swing.BoxLayout.Y_AXIS));
        scrollPanelEventos.setViewportView(boxPanelBoletos);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mis Boletos");

        btnRevender.setBackground(new java.awt.Color(0, 0, 0));
        btnRevender.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnRevender.setForeground(new java.awt.Color(255, 255, 255));
        btnRevender.setText("Revender");
        btnRevender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRevender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEventosLayout = new javax.swing.GroupLayout(pnlEventos);
        pnlEventos.setLayout(pnlEventosLayout);
        pnlEventosLayout.setHorizontalGroup(
            pnlEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEventosLayout.createSequentialGroup()
                .addGroup(pnlEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEventosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlEventosLayout.createSequentialGroup()
                        .addGroup(pnlEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEventosLayout.createSequentialGroup()
                                .addGap(232, 232, 232)
                                .addComponent(btnRevender, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlEventosLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(scrollPanelEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlEventosLayout.setVerticalGroup(
            pnlEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEventosLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanelEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRevender, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 886, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlEventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlEventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 886, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 886, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRevenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevenderActionPerformed
        try {
            for (PnlBoletoReventa pnlBoleto : listaPaneles) {
                if (pnlBoleto.getTxtFechaLimite().getText().isBlank() || pnlBoleto.getTxtPrecio().getText().isBlank()) {
                    JOptionPane.showMessageDialog(
                            this,
                            "Asegurese de llenar todos los campos",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if (Double.parseDouble(pnlBoleto.getTxtPrecio().getText()) > pnlBoleto.getBoleto().getPrecioOriginal() * 1.03) {
                    JOptionPane.showMessageDialog(
                            this,
                            "El precio no puede superar al 103% del precio original",
                            "ERROR",
                            JOptionPane.ERROR_MESSAGE
                    );
                    return;
                } else if (Double.parseDouble(pnlBoleto.getTxtPrecio().getText()) <= 0) {
                    JOptionPane.showMessageDialog(
                            this,
                            "No puede ingresar precios negativos o 0",
                            "ERROR",
                            JOptionPane.ERROR_MESSAGE
                    );
                    return;
                }
                if (!Seguridad.validaFecha(pnlBoleto.getTxtFechaLimite().getText())) {
                    JOptionPane.showMessageDialog(
                            this,
                            "El formato de la fecha debe ser dd/mm/yyyy",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            for (PnlBoletoReventa pnlBoleto : listaPaneles) {
                Double precio = Double.parseDouble(pnlBoleto.getTxtPrecio().getText());
                java.sql.Date fechaLimite = new java.sql.Date(Seguridad.dateMapper(pnlBoleto.getTxtFechaLimite().getText()).getTime());
                control.reventaBoleto(parent.getUsuario(),precio, pnlBoleto.getBoleto(), fechaLimite);
            }
            JOptionPane.showMessageDialog(
                            this,
                            "Se han puesto en reventa los boletos",
                            "Información",
                            JOptionPane.INFORMATION_MESSAGE);
                    
            parent.mostrarInicio();
        } catch (NumberFormatException err) {
            JOptionPane.showMessageDialog(
                    this,
                    "El formato del precio debe ser un decimal",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;

        }

    }//GEN-LAST:event_btnRevenderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boxPanelBoletos;
    private javax.swing.JButton btnRevender;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlEventos;
    private javax.swing.JScrollPane scrollPanelEventos;
    // End of variables declaration//GEN-END:variables
}
